export const ACTIONS = {
    FIND_REPOSITORIES_BY_SEARCH_STRING: "REPOSITORIES/FIND_REPOSITORIES_BY_SEARCH_STRING",
    FIND_VIEWER_REPOSITORY: "REPOSITORIES/FIND_VIEWER_REPOSITORY",
    FIND_REPOSITORIES_BY_ID: "REPOSITORIES/FIND_REPOSITORIES_BY_ID"
} as const;